---
galaxy_info:
  role_name: docker
  description: Install Docker and the docker-compose plugin on Amazon Linux 2
  author: cncloud team
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Amazon
      versions:
        - "2"

dependencies: []
